//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malfunctions
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Problem { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Process { get; set; }
        public bool Status { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhone { get; set; }
    }
}
