//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MalfunctionUpdate
    {
        public int Id { get; set; }
        public string SerialNo { get; set; }
        public string Process { get; set; }
    }
}
